### ISSUE TITLE
Dataset links expired?

### ISSUE THREAD

**Issue by jens321** [dungeonsdatasubmission/dungeonsdata-neurips2022#1]
Hi there,

Is it possible the links to the dataset files have expired? I get the following message from wetransfer when I click the link:
```
Transfer expired
Sorry, this transfer has expired and is not available any more
```

Would it be possible to fix the link? Thank you!

**Comment by jens321** [comment]
Thank you for fixing the NLD_NAO links! It does seem like the NLD-AA is still broken? Thanks for the help!

**Comment by dungeonsdatasubmission** [comment]
All fixed now! Thanks @jens321 for raising the issue, good luck with the data. :)

**Comment by luigiquara** [comment]
Hello,

It seems that the links are broken again.
Is it possible to restore them? Thank you!
