### ISSUE TITLE
[FEATURE REQUEST] Possible to include NLE gym information in NLD-AA?

### ISSUE THREAD

**Issue by jens321** [dungeonsdatasubmission/dungeonsdata-neurips2022#2]
**Request:** Since the NLD-AA dataset was generated by the symbolic-bot winner of the NeurIPS 2021 NetHack Competition, would it be possible to include the NLE gym-provided information such as glyphs, inventory glyphs, specials, etc for this part of the dataset? 

This could provide agents with a lot more information, especially since the inventory is currently only included in the `tty_chars` when the input command happened to be 'i'. 

Thank you for any thoughts!

**Comment by cdmatters** [comment]
If you need to regenerate the runs, they are done with the winner of the NetHack Challenge - code is here: https://github.com/maciej-sypetkowski/autoascend

A warning: we are able to collect terminal data for these trajectories by recording the terminal and saving as a ttyrec.  Ttyrecs are highly compressed (see the paper) as they are effectively storing ‘diffs’ of the different screen states, and then compressing them with bzip2. Our dataset loader loads and decompresses these on-the-fly. 

If you are still keen on being in the ‘big data’ regime, you may run out of disk space early and may have a hard time loading and unloading.  Its very possible that running efficiently on 90% correct inferred glyphs/inventories gets you better/faster results than running on fewer ‘recorded’ glyphs. Just a thought.

If you urgently need inventory,  and think you could have a scheme for storing the inventory efficiently in the ttyrec, I am open to considering pull requests.

**Comment by cdmatters** [comment]
I should note that most humans who play need to press 'i' to view the inventory, so philosophically we are keen to move away from presenting all the other gym informtion in the ttyrec - in principle we'd like machines to learn just from chars, colors, cursor where possible
